export type Difficulty = 'easy' | 'medium' | 'hard';

export interface Word {
  word: string;
  difficulty: Difficulty;
}

export const words: Word[] = [
  // Easy words (100)
  { word: 'chat', difficulty: 'easy' },
  { word: 'soleil', difficulty: 'easy' },
  { word: 'maison', difficulty: 'easy' },
  { word: 'voiture', difficulty: 'easy' },
  { word: 'arbre', difficulty: 'easy' },
  { word: 'chien', difficulty: 'easy' },
  { word: 'livre', difficulty: 'easy' },
  { word: 'cœur', difficulty: 'easy' },
  { word: 'étoile', difficulty: 'easy' },
  { word: 'fleur', difficulty: 'easy' },
  { word: 'lune', difficulty: 'easy' },
  { word: 'nuage', difficulty: 'easy' },
  { word: 'pomme', difficulty: 'easy' },
  { word: 'ballon', difficulty: 'easy' },
  { word: 'crayon de couleur', difficulty: 'easy' },
  { word: 'chaise', difficulty: 'easy' },
  { word: 'table', difficulty: 'easy' },
  { word: 'porte', difficulty: 'easy' },
  { word: 'fenêtre', difficulty: 'easy' },
  { word: 'clé', difficulty: 'easy' },
  { word: 'chapeau', difficulty: 'easy' },
  { word: 'chaussure', difficulty: 'easy' },
  { word: 'main', difficulty: 'easy' },
  { word: 'pied', difficulty: 'easy' },
  { word: 'œil', difficulty: 'easy' },
  { word: 'nez', difficulty: 'easy' },
  { word: 'bouche', difficulty: 'easy' },
  { word: 'tête', difficulty: 'easy' },
  { word: 'eau', difficulty: 'easy' },
  { word: 'feu', difficulty: 'easy' },
  { word: 'pont', difficulty: 'easy' },
  { word: 'bateau', difficulty: 'easy' },
  { word: 'train', difficulty: 'easy' },
  { word: 'voiture de course', difficulty: 'easy' },
  { word: 'oiseau', difficulty: 'easy' },
  { word: 'poisson', difficulty: 'easy' },
  { word: 'lapin', difficulty: 'easy' },
  { word: 'ours', difficulty: 'easy' },
  { word: 'lion', difficulty: 'easy' },
  { word: 'éléphant', difficulty: 'easy' },
  { word: 'girafe', difficulty: 'easy' },
  { word: 'banane', difficulty: 'easy' },
  { word: 'orange', difficulty: 'easy' },
  { word: 'fraise', difficulty: 'easy' },
  { word: 'cerise', difficulty: 'easy' },
  { word: 'tomate', difficulty: 'easy' },
  { word: 'pain', difficulty: 'easy' },
  { word: 'fromage', difficulty: 'easy' },
  { word: 'gâteau', difficulty: 'easy' },
  { word: 'glace', difficulty: 'easy' },
  { word: 'crayon', difficulty: 'easy' },
  { word: 'gomme', difficulty: 'easy' },
  { word: 'règle', difficulty: 'easy' },
  { word: 'ciseaux', difficulty: 'easy' },
  { word: 'colle', difficulty: 'easy' },
  { word: 'cahier', difficulty: 'easy' },
  { word: 'stylo', difficulty: 'easy' },
  { word: 'feuille', difficulty: 'easy' },
  { word: 'crayon à papier', difficulty: 'easy' },
  { word: 'marqueur', difficulty: 'easy' },
  { word: 'pinceau', difficulty: 'easy' },
  { word: 'peinture', difficulty: 'easy' },
  { word: 'couleur', difficulty: 'easy' },
  { word: 'rouge', difficulty: 'easy' },
  { word: 'bleu', difficulty: 'easy' },
  { word: 'vert', difficulty: 'easy' },
  { word: 'jaune', difficulty: 'easy' },
  { word: 'rose', difficulty: 'easy' },
  { word: 'violet', difficulty: 'easy' },
  { word: 'noir', difficulty: 'easy' },
  { word: 'blanc', difficulty: 'easy' },
  { word: 'gris', difficulty: 'easy' },
  { word: 'marron', difficulty: 'easy' },
  { word: 'roue', difficulty: 'easy' },
  { word: 'moto', difficulty: 'easy' },
  { word: 'camion', difficulty: 'easy' },
  { word: 'bus', difficulty: 'easy' },
  { word: 'métro', difficulty: 'easy' },
  { word: 'taxi', difficulty: 'easy' },
  { word: 'bateau à voile', difficulty: 'easy' },
  { word: 'sous-marin', difficulty: 'easy' },
  { word: 'fusée', difficulty: 'easy' },
  { word: 'satellite', difficulty: 'easy' },
  { word: 'planète', difficulty: 'easy' },
  { word: 'comète', difficulty: 'easy' },
  { word: 'galaxie', difficulty: 'easy' },
  { word: 'trou noir', difficulty: 'easy' },
  { word: 'astronaute', difficulty: 'easy' },
  { word: 'étoile filante', difficulty: 'easy' },
  { word: 'aurore boréale', difficulty: 'easy' },
  { word: 'météore', difficulty: 'easy' },
  { word: 'jumelles', difficulty: 'easy' },
  { word: 'loupe', difficulty: 'easy' },
  { word: 'boussole', difficulty: 'easy' },
  { word: 'montre', difficulty: 'easy' },
  { word: 'réveil', difficulty: 'easy' },
  { word: 'pendule', difficulty: 'easy' },
  { word: 'calendrier', difficulty: 'easy' },
  { word: 'agenda', difficulty: 'easy' },
  { word: 'carnet', difficulty: 'easy' },

  // Medium words (100)
  { word: 'avion', difficulty: 'medium' },
  { word: 'téléphone', difficulty: 'medium' },
  { word: 'guitare', difficulty: 'medium' },
  { word: 'château', difficulty: 'medium' },
  { word: 'montagne', difficulty: 'medium' },
  { word: 'vélo', difficulty: 'medium' },
  { word: 'café', difficulty: 'medium' },
  { word: 'parapluie', difficulty: 'medium' },
  { word: 'horloge', difficulty: 'medium' },
  { word: 'crayon', difficulty: 'medium' },
  { word: 'piano', difficulty: 'medium' },
  { word: 'violon', difficulty: 'medium' },
  { word: 'trompette', difficulty: 'medium' },
  { word: 'batterie', difficulty: 'medium' },
  { word: 'caméra', difficulty: 'medium' },
  { word: 'appareil photo', difficulty: 'medium' },
  { word: 'microphone', difficulty: 'medium' },
  { word: 'radio', difficulty: 'medium' },
  { word: 'réfrigérateur', difficulty: 'medium' },
  { word: 'four', difficulty: 'medium' },
  { word: 'machine à laver', difficulty: 'medium' },
  { word: 'aspirateur', difficulty: 'medium' },
  { word: 'fer à repasser', difficulty: 'medium' },
  { word: 'sèche-cheveux', difficulty: 'medium' },
  { word: 'brosse à dents', difficulty: 'medium' },
  { word: 'savon', difficulty: 'medium' },
  { word: 'serviette', difficulty: 'medium' },
  { word: 'oreiller', difficulty: 'medium' },
  { word: 'couverture', difficulty: 'medium' },
  { word: 'lampe', difficulty: 'medium' },
  { word: 'bougie', difficulty: 'medium' },
  { word: 'miroir', difficulty: 'medium' },
  { word: 'tableau', difficulty: 'medium' },
  { word: 'photo', difficulty: 'medium' },
  { word: 'cadre', difficulty: 'medium' },
  { word: 'vase', difficulty: 'medium' },
  { word: 'plante', difficulty: 'medium' },
  { word: 'jardin', difficulty: 'medium' },
  { word: 'piscine', difficulty: 'medium' },
  { word: 'plage', difficulty: 'medium' },
  { word: 'océan', difficulty: 'medium' },
  { word: 'rivière', difficulty: 'medium' },
  { word: 'lac', difficulty: 'medium' },
  { word: 'forêt', difficulty: 'medium' },
  { word: 'désert', difficulty: 'medium' },
  { word: 'volcan', difficulty: 'medium' },
  { word: 'cascade', difficulty: 'medium' },
  { word: 'arc-en-ciel', difficulty: 'medium' },
  { word: 'tempête', difficulty: 'medium' },
  { word: 'éclair', difficulty: 'medium' },
  { word: 'tonnerre', difficulty: 'medium' },
  { word: 'grêle', difficulty: 'medium' },
  { word: 'neige', difficulty: 'medium' },
  { word: 'gel', difficulty: 'medium' },
  { word: 'brouillard', difficulty: 'medium' },
  { word: 'rosée', difficulty: 'medium' },
  { word: 'vent', difficulty: 'medium' },
  { word: 'ouragan', difficulty: 'medium' },
  { word: 'tornade', difficulty: 'medium' },
  { word: 'tsunami', difficulty: 'medium' },
  { word: 'séisme', difficulty: 'medium' },
  { word: 'tremblement de terre', difficulty: 'medium' },
  { word: 'éruption', difficulty: 'medium' },
  { word: 'lave', difficulty: 'medium' },
  { word: 'cratère', difficulty: 'medium' },
  { word: 'geyser', difficulty: 'medium' },
  { word: 'source chaude', difficulty: 'medium' },
  { word: 'grotte', difficulty: 'medium' },
  { word: 'caverne', difficulty: 'medium' },
  { word: 'stalactite', difficulty: 'medium' },
  { word: 'stalagmite', difficulty: 'medium' },
  { word: 'falaise', difficulty: 'medium' },
  { word: 'ravin', difficulty: 'medium' },
  { word: 'vallée', difficulty: 'medium' },
  { word: 'colline', difficulty: 'medium' },
  { word: 'plateau', difficulty: 'medium' },
  { word: 'prairie', difficulty: 'medium' },
  { word: 'savane', difficulty: 'medium' },
  { word: 'jungle', difficulty: 'medium' },
  { word: 'toundra', difficulty: 'medium' },
  { word: 'banquise', difficulty: 'medium' },
  { word: 'glacier', difficulty: 'medium' },
  { word: 'iceberg', difficulty: 'medium' },
  { word: 'fjord', difficulty: 'medium' },
  { word: 'île', difficulty: 'medium' },
  { word: 'presqu\'île', difficulty: 'medium' },
  { word: 'archipel', difficulty: 'medium' },
  { word: 'atoll', difficulty: 'medium' },
  { word: 'récif corallien', difficulty: 'medium' },
  { word: 'barrière de corail', difficulty: 'medium' },
  { word: 'marais', difficulty: 'medium' },
  { word: 'marais salant', difficulty: 'medium' },
  { word: 'étang', difficulty: 'medium' },
  { word: 'mare', difficulty: 'medium' },
  { word: 'ruisseau', difficulty: 'medium' },
  { word: 'torrent', difficulty: 'medium' },
  { word: 'rapide', difficulty: 'medium' },
  { word: 'delta', difficulty: 'medium' },
  { word: 'estuaire', difficulty: 'medium' },
  { word: 'canyon', difficulty: 'medium' },

  // Hard words (100)
  { word: 'architecture', difficulty: 'hard' },
  { word: 'télévision', difficulty: 'hard' },
  { word: 'ordinateur', difficulty: 'hard' },
  { word: 'bibliothèque', difficulty: 'hard' },
  { word: 'pharmacie', difficulty: 'hard' },
  { word: 'ascenseur', difficulty: 'hard' },
  { word: 'hélicoptère', difficulty: 'hard' },
  { word: 'microscope', difficulty: 'hard' },
  { word: 'télescope', difficulty: 'hard' },
  { word: 'laboratoire', difficulty: 'hard' },
  { word: 'stéthoscope', difficulty: 'hard' },
  { word: 'thermomètre', difficulty: 'hard' },
  { word: 'tensiomètre', difficulty: 'hard' },
  { word: 'scalpel', difficulty: 'hard' },
  { word: 'centrifugeuse', difficulty: 'hard' },
  { word: 'incubateur', difficulty: 'hard' },
  { word: 'autoclave', difficulty: 'hard' },
  { word: 'spectromètre', difficulty: 'hard' },
  { word: 'chromatographe', difficulty: 'hard' },
  { word: 'électrocardiogramme', difficulty: 'hard' },
  { word: 'imprimante 3D', difficulty: 'hard' },
  { word: 'scanner', difficulty: 'hard' },
  { word: 'imprimante', difficulty: 'hard' },
  { word: 'clavier', difficulty: 'hard' },
  { word: 'souris', difficulty: 'hard' },
  { word: 'écran', difficulty: 'hard' },
  { word: 'haut-parleur', difficulty: 'hard' },
  { word: 'casque audio', difficulty: 'hard' },
  { word: 'enceinte', difficulty: 'hard' },
  { word: 'amplificateur', difficulty: 'hard' },
  { word: 'mixeur', difficulty: 'hard' },
  { word: 'robot ménager', difficulty: 'hard' },
  { word: 'lave-vaisselle', difficulty: 'hard' },
  { word: 'lave-linge', difficulty: 'hard' },
  { word: 'sèche-linge', difficulty: 'hard' },
  { word: 'congélateur', difficulty: 'hard' },
  { word: 'radiateur', difficulty: 'hard' },
  { word: 'climatiseur', difficulty: 'hard' },
  { word: 'chauffage', difficulty: 'hard' },
  { word: 'chaudière', difficulty: 'hard' },
  { word: 'panneau solaire', difficulty: 'hard' },
  { word: 'éolienne', difficulty: 'hard' },
  { word: 'générateur', difficulty: 'hard' },
  { word: 'transformateur', difficulty: 'hard' },
  { word: 'circuit électrique', difficulty: 'hard' },
  { word: 'fusible', difficulty: 'hard' },
  { word: 'interrupteur', difficulty: 'hard' },
  { word: 'prise électrique', difficulty: 'hard' },
  { word: 'multiprise', difficulty: 'hard' },
  { word: 'paratonnerre', difficulty: 'hard' },
  { word: 'disjoncteur', difficulty: 'hard' },
  { word: 'compteur électrique', difficulty: 'hard' },
  { word: 'tableau électrique', difficulty: 'hard' },
  { word: 'câble électrique', difficulty: 'hard' },
  { word: 'fil électrique', difficulty: 'hard' },
  { word: 'prise multiple', difficulty: 'hard' },
  { word: 'rallonge électrique', difficulty: 'hard' },
  { word: 'adaptateur', difficulty: 'hard' },
  { word: 'convertisseur', difficulty: 'hard' },
  { word: 'onduleur', difficulty: 'hard' },
  { word: 'batterie rechargeable', difficulty: 'hard' },
  { word: 'chargeur', difficulty: 'hard' },
  { word: 'câble USB', difficulty: 'hard' },
  { word: 'câble HDMI', difficulty: 'hard' },
  { word: 'câble Ethernet', difficulty: 'hard' },
  { word: 'routeur', difficulty: 'hard' },
  { word: 'modem', difficulty: 'hard' },
  { word: 'switch réseau', difficulty: 'hard' },
  { word: 'point d\'accès Wi-Fi', difficulty: 'hard' },
  { word: 'antenne parabolique', difficulty: 'hard' },
  { word: 'récepteur satellite', difficulty: 'hard' },
  { word: 'décodeur', difficulty: 'hard' },
  { word: 'enregistreur vidéo', difficulty: 'hard' },
  { word: 'lecteur DVD', difficulty: 'hard' },
  { word: 'lecteur Blu-ray', difficulty: 'hard' },
  { word: 'console de jeu', difficulty: 'hard' },
  { word: 'manette de jeu', difficulty: 'hard' },
  { word: 'casque VR', difficulty: 'hard' },
  { word: 'lunettes 3D', difficulty: 'hard' },
  { word: 'projecteur', difficulty: 'hard' },
  { word: 'écran tactile', difficulty: 'hard' },
  { word: 'tablette graphique', difficulty: 'hard' },
  { word: 'webcam', difficulty: 'hard' },
  { word: 'micro-casque', difficulty: 'hard' },
  { word: 'station d\'accueil', difficulty: 'hard' },
  { word: 'hub USB', difficulty: 'hard' },
  { word: 'lecteur de carte', difficulty: 'hard' },
  { word: 'disque dur externe', difficulty: 'hard' },
  { word: 'clé USB', difficulty: 'hard' },
  { word: 'carte mémoire', difficulty: 'hard' },
  { word: 'lecteur optique', difficulty: 'hard' },
  { word: 'graveur de disque', difficulty: 'hard' },
  { word: 'serveur', difficulty: 'hard' },
  { word: 'NAS', difficulty: 'hard' },
  { word: 'imprimante laser', difficulty: 'hard' },
  { word: 'imprimante à jet d\'encre', difficulty: 'hard' },
  { word: 'scanner à plat', difficulty: 'hard' },
  { word: 'photocopieuse', difficulty: 'hard' },
  { word: 'fax', difficulty: 'hard' },
  { word: 'télécopieur', difficulty: 'hard' },
];

export function getWordsByDifficulty(difficulty: Difficulty): Word[] {
  return words.filter(word => word.difficulty === difficulty);
}

export function getRandomWord(difficulty: Difficulty): Word {
  const filteredWords = getWordsByDifficulty(difficulty);
  const randomIndex = Math.floor(Math.random() * filteredWords.length);
  return filteredWords[randomIndex];
}
